cloudfour/drizzle-builder

package.json
src/options.js
src/parse.js
test/fixtures/docs/doThis.md
test/options.js
test/parse.js

This single-feature PR (you know, like it should be) adds the ability to parse and build data from docs files. By default it will run `marked` over these but provides a new `option` for using a different parsing function if so desired.

Feature: Parse Docs

---

src/index.js
src/options.js
src/parse.js
test/config.js
test/index.js
test/options.js
test/parse-all.js
test/parse.js

This is a rather dull but functional PR, integrating several chunks of parsing into a exported function for consumption by the main (index) module.
The structure of this context object is going to change—notably, we're changing how we handle `docs` and `pages`—but the generalized functionality (generate a context object and prepare some templates stuff) is the approach to preparing to do the actual build.
As we iron this stuff out, I expect to see the `parseAll` function get cleaner and friendlier. It's helping to show me where there are places that could be refactored better.
/cc @erikjung

Context Stubbing

---

package.json
src/options.js
test/options.js

All right, I've had it. The expense of backwards-compatibility on the options parsing isn't worth it.
This PR greatly simplifies options merging, and uses the `deepmerge` package to do it (one of the few utility dependencies in the project). I'll take the task of porting any existing fabricator setups to use the new options.
The options object in this PR isn't at its end state; it's flat and ugly. I want to merge this and then rebase my working branch onto it and make it beautiful.
Note that there are extremely minimal tests on this options module at present; I'll add on my feature branch.

Redo Options, Seriously :)

---

src/options.js
src/parse.js
src/utils.js
test/config.js
test/fixtures/patterns/01-fingers/pamp.html
test/options.js
test/parse-all.js
test/parse.js
test/utils.js

This PR is not in a golden state yet, but I don't wish it to get too huge. It introduces the idea of "parsers", a way to define how different kinds of files get, well, parsed and built into a data object as preparation for output.
There's still cleanup to do—`docs` are sort of meaningless at this point, more tests need to be written—but the core concept is in place: the ability to define custom parsers for different file types should you wish to. This simplifies the whole notion of parsing files out of `pages`, `patterns`, and `data`. Instead of having a bunch of specialized parsing functions, we can generalize the parsing behavior. There are a set of default parsers, but they can all be overridden, or new ones can be added. 
Keep in mind that this is just about parsing. Generating (i.e. …

Add Parsers

---

src/options.js
src/parse.js
src/utils.js
test/config.js
test/fixtures/pages/components.html
test/options.js
test/parse-all.js
test/parse.js

This admittedly-mundane PR massages the shapes of the context objects being generated for patterns and pages so that I can move into beginning to output things. It's mostly concerned with creating correctly-nested and -keyed objects for later traversal and use. 
It's pretty boring.
But it was kind of hard.
zzzzzz recursion...
/cc @mrgerardorodriguez

Munge Context Object Structure

---

package.json
src/index.js
src/options.js
src/pages.js
src/parse.js
src/prepare.js
src/template.js
src/utils.js
test/config.js
test/fixtures/pages/04-sandbox.html
test/fixtures/pages/components.html
test/index.js
test/options.js
test/pages.js
test/parse-all.js
test/parse.js
test/prepare.js

What it does: parses files matching glob for `pages` against relevant parsers, builds relevant local and global contexts, compiles pages as Handlebars templates, writes output files (pages).
What it doesn't do (yet): Wrap resulting page files in a containing layout.
I wanted to submit a PR of the basic bits of this feature before it got _too_ huge.  As such, certain things are in TODO/loose state, including:
* Organization of several modules, which need to be broken into submodules
* Commenting, clarity
* Full suite of tests (basic tests are extant but need significant expansion)
* A few temporary-named functions as I re-orient some of the parsing functions
Next step is a widespread module cleanup, reorg of modules, testing, and then page wrapping in layouts.
We're in that "so much green" …

Basic Pages Output

---

src/parse/index.js
src/parse/layouts.js
src/parse/pages.js
src/parse/patterns.js
src/parse/utils.js
src/prepare/partials.js
src/prepare/patterns.js
src/prepare/templates.js
src/render/patterns.js
src/utils.js
test/fixtures/layouts/patternCollection.html
test/fixtures/patterns/typography/headings/base.html
test/parse/index.js
test/parse/layouts.js
test/parse/patterns.js
test/prepare/index.js
test/prepare/layouts.js
test/prepare/patterns.js
test/render/patterns.js
test/utils.js

Hi! This PR introduces some features around `rendering` `patterns`, that is, constructing an object that represents what should ultimately be output as HTML pages. It does not handle the actual writing to the file system yet; to keep this PR from getting too huge I'd like to do that separately.
The main point: a directory under the main `patterns` directory that contains direct-descendent pattern files is considered a `collection` and will generate an output HTML page using a template that can iterate over the collection's patterns and output them. This PR handles the rendering part of that—compiling the right templates with the right context—but not the filesystem output yet.
When reviewing this, it may be helpful to know/remember that `drizzle` executes in four _phases_:
* `prepare` — …

Feature patterns parsing

---

package.json
src/parse/patterns.js
src/render/index.js
src/render/pages.js
src/render/patterns.js
src/write/patterns.js
test/fixtures/layouts/patternCollection.html
test/index.js
test/parse/patterns.js
test/render/index.js
test/render/pages.js
test/render/patterns.js
test/test-utils.js
test/write/pages.js
test/write/patterns.js

This PR introduces support for basic file output for pattern-collection pages. The next step will be to architect the `pattern` helper (analogous to the `material` helper) to embed patterns into pattern-collection pages in a more full-featured way. I also have some further work to do with massaging local context when compiling templates, but we're headed the right way.
This PR:
* Adds a `write/patterns` module for writing out the pattern-collections pages.
* Removes the borken `chai-fs` package, leaving no good option for third-party file-testing assertions. So I wrote some hokey basic file-checking utility functions in a new file `test/test-utils.js`.
* Adds `rimraf` dependency and use it to clear out `dist` in the `test` directory—that is, remove pre-existing test output before running …

Feature: Write Pattern Collections to FS

---

src/defaults.js
src/helpers/pattern.js
src/parse/collections.js
src/parse/patterns.js
src/prepare/helpers.js
src/prepare/patterns.js
src/render/collections.js
src/render/context/collection.js
src/render/context/page.js
src/render/context/pattern.js
src/render/index.js
src/render/pages.js
src/utils.js
test/config.js
test/fixtures/layouts/patternCollection.html
test/fixtures/pages/components.html
test/fixtures/patterns/components/button/aardvark.html
test/fixtures/patterns/components/button/base.html
test/fixtures/patterns/components/button/collection.yml
test/fixtures/patterns/components/button/color-variation.html
test/fixtures/patterns/components/button/disabled.html
test/parse/patterns.js
test/prepare/index.js
test/render/collections.js
test/render/context/pattern.js

This is a pretty chunky PR that establishes the foundation of being able to embed patterns with the correct context, via the `pattern` helper as well as other context tools. It also introduces some rudimentary `collection` metadata control, which I'll expand upon. It also more concretely uses the notion of collections overall, as they are more pervasive than our starting point suggested. Still, this is not particularly interesting code, functional, so I'm not looking for a terribly deep assessment :). 
I have started throwing in tests, but commenting and clarity could definitely use some attention!
/cc @erikjung

Pattern helper and main context

---

src/defaults.js
src/parse/patterns/pattern.js
src/parse/patterns/patterns.js
src/utils/parse.js
test/fixtures/patterns/fingers/ideal.html
test/options.js
test/parse/patterns/patterns.js
test/utils/parse.js

This PR introduces the ability to "parse" front matter fields in patterns, and there are two ways to do it, which I hope will generally please folks. I can also expand this feature to `pages` (it probably should be done for consistency's sake).
This feature was created to address #3 but is more generic and extensible should there be other desires to process field contents beyond `markdown`.
The builder function takes a `fieldParsers` option, which is an object mapping field names to "parser keys". Default parsers are [in src/parse/parsers.js](https://github.com/cloudfour/drizzle-builder/blob/feature-field-parsing/src/parse/parsers.js) and can also be extended with options (`parsers` option). But, anyway, default parsers include `markdown`, `yaml`, etc. Let's concentrate on `markdown` for …

Field parsing

---

src/utils/write.js
src/write/collections.js
src/write/index.js
src/write/pages.js
test/fixtures/pages/follow-me/down/apage.md
test/utils/write.js
test/write/collections.js
test/write/pages.js

BOOOORING PR to refactor some code, add comments, clean up, DRY stuff out and add more tests to the `write` modules.
I was _so_ close to being able to generalize the recursive walking in the `pages` and `collections` write modules, but, just, not so much...too much can o' worms there. Still, not very long functions in either case.

Chore: Clean Up Write Modules

---

package.json

We should make sure the `dist` is included in the module since that's what `main` points to.
/CC @mrgerardorodriguez

Update package.json (files)

---

package.json
src/helpers/pattern.js
src/init.js
src/parse/index.js
src/parse/patterns.js
src/prepare/helpers.js
src/prepare/index.js
src/prepare/partials.js
src/render/index.js
src/utils/error.js
src/utils/object.js
src/utils/parse.js
src/write/collections.js
src/write/index.js
src/write/pages.js
test/config.js
test/prepare/helpers.js
test/prepare/index.js
test/prepare/partials.js
test/utils/error.js
test/utils/object.js
test/write/collections.js

This PR introduces some sort of consistent error handling across the package.
* `npm test` now adds an environment variable (`DRIZZLE_DEBUG`) which is used to make all errors throw by default. This aids in testability.
* `DrizzleError` extends `Error`. Errors can also be dispatched with a static method, `DrizzleError.error`.
* Several places will spawn WARN errors now—duplicate partial keys will be noted, e.g.
* Promise chains have `catch` functions now, which use `DrizzleError` to handle errors that arise.
* Tests pass and additional tests have been added for `utils/error`.
* Several pending tests fulfilled now.

Better Error Handling

---

src/render/pages.js
test/render/pages.js

This fixes an error @erikjung ran into if a page source file is empty. With fixture and tests.

Fix recursion error on empty page files

---

src/defaults.js
src/parse/index.js
src/parse/patterns.js
src/parse/tree.js
src/render/index.js
src/utils/parse.js
src/utils/shared.js
src/utils/write.js
src/write/collections.js
src/write/pages.js
test/config.js
test/init.js
test/parse/index.js
test/parse/patterns.js
test/parse/tree.js
test/render/index.js
test/utils/shared.js
test/write/collections.js

I don't consider this feature fully-baked, but there are enough elements of it that I want to get it merged into place for you guys.
The top-level `drizzle` object available in template contexts now has a `tree` property, which has, at present, two sub-objects (`pages` and `collections`). These objects are structured in a more useful way to generate navigation. They are structured like (I'm going to write this in YAML for speed savings):
```
pages:
items:
- id: pages.index
key: index
path: ./dist/index.html
- id: pages.another-page
key: another-page
path: .dist/another-page.html
children:
items: ...
children: ...
items: ...
children: ...
```
You'll note the `path` properties aren't completely useful yet—they're calculated based on the `dest` options passed. We'll want to circle back when …

Nav Tree Structure

---

src/init.js

Re: #77 
This change to `init()` indirectly fixes the prompts about duplicate helpers/partials by using a new Handlebars instance each time Drizzle is started (if no `handlebars` instance argument is supplied).

Fix: Silent Handlebars helper/partial console warnings when used w/ Gulp

---

src/helpers/data.js
src/prepare/helpers.js
test/fixtures/data/people.yaml
test/fixtures/pages/usingHelpers.html
test/prepare/helpers.js
test/write/pages.js

This introduces a new Handlebars inline helper that will be available to Drizzle templates.
The purpose of the helper is to provide a more terse method of accessing data. It's simply a shortcut to referencing `{{drizzle.data.filename.contents.key...}}`, allowing access by this method instead:
```{{data "filename.key..."}}```
Some examples:
```hbs
{{#with (data "projects.latest.2")}}
{{title}}
{{/with}}
{{#each (data "people")}}
{{name}}: {{age}}
{{/each}}
{{data "articles.0.category"}}
```
/CC @mrgerardorodriguez @tylersticka @nicolemors @saralohr

Feature: Add data shortcut helper

---

package.json
src/defaults.js
src/helpers/page.js
src/prepare/helpers.js
src/utils/list.js
src/utils/object.js
src/utils/shared.js
test/config.js
test/fixtures/pages/follow-me/down/apage.md
test/fixtures/pages/follow-me/down/orthree.md
test/fixtures/pages/follow-me/down/ortwo.md
test/fixtures/pages/usingPageHelpers.html
test/init.js
test/test-utils.js
test/write/pages.js

Re: https://github.com/cloudfour/drizzle/issues/23, #83 
This adds two new Handlebars helpers:
- `{{page}}`
- `{{pages}}`
They both return a data context (object or array), and are intended to be combined with `{{#with}}` and `{{#each}}`. The purpose of them is to provide a more convenient/flexible way to generate a listing of menu items (including `url` values).
```hbs
{{#each (pages ".")}}
<li>
<a class="drizzle-Nav-item" href="{{baseurl}}/{{url}}">
{{data.title}}
</a>
</li>
{{/each}}
```
```hbs
{{#each (pages "demos/examples" sortby="order" ignore="index")}}
<li>
<a class="drizzle-Nav-item" href="{{baseurl}}/{{url}}">
{{data.title}}
</a>
</li>
{{/each}}
```
```hbs
{{#with (page "demos/index")}}
<a class="drizzle-Nav-item" href="{{baseurl}}/{{url}}">
{{data.title}}
</a>
{{/with}}
``` …

Feature: page helpers

---

src/render/pages.js
test/fixtures/templates/collection.html
test/fixtures/templates/default.html
test/fixtures/templates/page.html

This PR is the first bit of work to address https://github.com/cloudfour/drizzle/issues/53. The goal is to use `main` as the main content block as opposed to `body`. 
cc: @erikjung @tylersticka

Feature: Change `body` block to `main`

---

src/helpers/page.js
src/parse/tree.js
src/utils/object.js
test/config.js
test/fixtures/pages/helpers-demo-collections.hbs
test/write/pages.js

Re: #88, #83, https://github.com/cloudfour/drizzle/issues/23
This adds a `{{collections}}` helper to assist in iterating over collections of patterns.
Like the `{{pages}}` and `{{data}}` helpers, this also accepts a path argument.
```hbs
{{#each (collections)}}
<li>
<a class="drizzle-Nav-item" href="{{baseurl}}/{{url}}">
{{name}}
</a>
</li>
{{/each}}
{{#each (collections "components")}}
<li>
<a class="drizzle-Nav-item" href="{{baseurl}}/{{url}}">
{{name}}
</a>
</li>
{{/each}}
{{#each (collections "typography")}}
<li>
<a class="drizzle-Nav-item" href="{{baseurl}}/{{url}}">
{{name}}
</a>
</li>
{{/each}}
```
Not at this time. The underlying structure for collections is different than that for pages, and doesn't have the same access to front matter at the directory level.
Related to the above …

Feature: add collections helper

---

src/utils/context.js

Re: #63, https://github.com/cloudfour/drizzle/issues/43
This change makes the `{{baseurl}}` template property have a value.
The value will be different depending on the location of each page, and will always be a relative path string pointing to the destination root directory (e.g. `dist`).
For example:
```hbs
<script src="{{baseurl}}/main.js">
```
```html
<script src="./main.js">
```
```hbs
<script src="{{baseurl}}/main.js">
```
```html
<script src="../../main.js">
```
This will allow the static HTML output to be viewed using the `file://` protocol without needing any server:
/CC @tylersticka @saralohr @nicolemors @aileenjeffries

Feature: Attach `baseurl` property to template context

---

src/helpers/string.js
src/prepare/helpers.js
test/fixtures/pages/helpers-demo-string.hbs
test/write/pages.js

Looking into the feasibility of using PostHTML to automatically prefix classes in HTML with `drizzle-` made me realize a challenge I hadn't considered. 
Because it would need to be done after the Handlebars rendering, there would be no way to differentiate Drizzle UI elements from patterns:
```html
<div class="u-pad u-cf u-posRelative ">
<button class="Button Button--primary">
Primary Button
</button>
</div>
```
All of the classes (even the pattern ones) would end up with the prefix. The PostHTML [plugin](https://github.com/stevenbenisek/posthtml-prefix-class) provides a way to ignore certain classes, but it doesn't seem applicable because the class naming schemes of both the patterns and the Drizzle UI are typically identical.
So, I thought another solution might be to rely on a …

Feature: Add `{{ns}}` helper and tests

---

package.json
test/utils/shared.js
test/utils/write.js
test/write/collections.js
test/write/pages.js

For #98 
- Added `cross-env` normalize use of environment vars in package.json scripts
- Added `chai-fs` to assist with some file path assertions
- Added `path.normalize` around a bunch of path string assertions
/CC @tylersticka

Fix issue 98

---

package-lock.json
package.json

Updates the `deep-extend` dependency to v0.5.1 to fix a security vulnerability in v0.4.1.

Update deep-extend dependency
